# Generated by Django 3.1.5 on 2021-01-29 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0005_drinks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Drinks',
            new_name='Drink',
        ),
    ]
