# Generated by Django 3.1.5 on 2021-01-29 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0007_b'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='b',
            name='user',
        ),
        migrations.DeleteModel(
            name='Drink',
        ),
        migrations.DeleteModel(
            name='B',
        ),
    ]
