# Generated by Django 3.1.5 on 2021-01-29 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0009_drink'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Drink',
        ),
    ]
